default_platform(:ios)

xcode_select "/Applications/Xcode.app"

platform :ios do
  desc “Upload screenshots”
  lane :screenshots do
    create_keychain(
      name: ENV['MATCH_KEYCHAIN_NAME'],
      password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 0,
      lock_when_sleeps: false
    )
    match(
      type: "appstore",
      readonly: false,
      keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
    )
    get_certificates
    get_provisioning_profile
    upload_to_app_store(
      skip_binary_upload: true,
      screenshots_path: "../screenshots/ios",
      overwrite_screenshots: true,
    )
  end
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    create_keychain(
      name: ENV['MATCH_KEYCHAIN_NAME'],
      password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 0,
      lock_when_sleeps: false
    )
    match(
      type: "appstore",
      readonly: false,
      keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
    )
    get_certificates
    get_provisioning_profile
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store"
    )
    upload_to_testflight
  end
end
