[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "requests>=2.32.3",
    "retry>=0.9.2",
]

[dependency-groups]
dev = [
    "ruff>=0.11.5",
]
